plugins:
  generators:
    rest.RestGenerator:
      uri: http://localhost:8000/query
      method: POST
      headers:
        Content-Type: application/json
      request_body_template:
        question: "{prompt}"
        debug: false
      response_field: answer

